[package]
name = "snake"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.19.0", features = ["persistence"] }
egui = { version = "0.19.0", features = ["persistence"] }
rand = "0.8.5"
